# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kavii

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kavii.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fe430d4187544e798a5c50b05bdb1bf4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6dd2bdbc731441dbae84ec2a2025b488 }}

    # - name: Build and push container image to registry
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: kavii.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fe430d4187544e798a5c50b05bdb1bf4 }}/nginx:${{ github.sha }}
    #     file: ./webapp-container/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    # needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kavii'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a2647e72d0e349279a958fbc932d98cb }}
        images: 'kavii.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fe430d4187544e798a5c50b05bdb1bf4 }}/nginx:f60a3921e60cfd2086186b10f07d73b6897b6e8e'
